name: DockerRedisAuth

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - DockerRedisAuth

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - DockerRedisAuth

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "9090:9090"
    depends_on:
      - mongo
      - redis
    networks:
      - DockerRedisAuth
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - DockerRedisAuth
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mongo_data:

networks:
  DockerRedisAuth:
    driver: bridge